### ISSUE TITLE
problem using the program

### ISSUE THREAD

**Issue by davcrox** [Juggernaut93/Projector2Assembler#1]
The program does not works : 

`Computing block definitions. Please wait...
Traceback (most recent call last):
  File "BlockDefinitionExtractor.py", line 372, in <module>
  File "BlockDefinitionExtractor.py", line 334, in main
  File "BlockDefinitionExtractor.py", line 247, in examinePackage
  File "BlockDefinitionExtractor.py", line 217, in getCubeBlocksTree
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'C:\\Users\\davcrox\\AppData\\Local\\Temp\\tmpf0l6tg9s\\Data'
[13744] Failed to execute script BlockDefinitionExtractor`
the folder has not been created

**Comment by Juggernaut93** [comment]
Hi, a fix has been pushed to the repo. Please try the [new release](https://github.com/Juggernaut93/Projector2Assembler/releases/tag/v1.0.1) and let me know if it works.

**Comment by davcrox** [comment]
still another problem, there is no default value for the map line 301, I get a key error : 

Computing block definitions. Please wait...
Traceback (most recent call last):
  File "C:\Users\davcrox\Downloads\Projector2Assembler-master\BlockDefinitionExtractor\BlockDefinitionExtractor.py", line 373, in <module>
    main()
  File "C:\Users\davcrox\Downloads\Projector2Assembler-master\BlockDefinitionExtractor\BlockDefinitionExtractor.py", line 342, in main
    blockDefinitionData = assembleBlockDefinitionData()
  File "C:\Users\davcrox\Downloads\Projector2Assembler-master\BlockDefinitionExtractor\BlockDefinitionExtractor.py", line 301, in assembleBlockDefinitionData
    subTypes = list(map(lambda x: bpnames[x], subTypes))
  File "C:\Users\davcrox\Downloads\Projector2Assembler-master\BlockDefinitionExtractor\BlockDefinitionExtractor.py", line 301, in <lambda>
    subTypes = list(map(lambda x: bpnames[x], subTypes))
KeyError: 'DeadTechiumProcessorCore'

**Comment by Juggernaut93** [comment]
Sorry, I will check this other issue tomorrow.

**Comment by Juggernaut93** [comment]
It looks like you are using [this mod](https://steamcommunity.com/sharedfiles/filedetails/?id=539471716), that adds a new building component, the "DeadTech Crate Core". Unfortunately, as stated on the Steam page of Projector2Assembler:

> The script can be made compatible with mods that modify or add new block definitions **(but without adding new kinds of components to be assembled in an Assembler)**

So this mod is not currently supported and I currently have no plans to add support for mods with new components in the immediate future for lack of time, since this addition would probably require major modifications to the code for all the scripts here.

EDIT: I have added an error message when using unsupported mods.
